<?php
namespace app\admin\controller\store;


use app\common\controller\Backend;

class Shops extends Backend
{
    protected $model = null;
    public function initialize()
    {
        $this -> model = new \app\common\model\Shops();
        return parent::initialize(); // TODO: Change the autogenerated stub
    }
    public function index(){
        if ($this->request->isAjax()) {
            [$where, $sort, $order, $offset, $limit] = $this->buildparams();
            $total = $this->model
                ->where($where)
//                ->order($sort, $order)
                ->count();
            $list = $this->model
                ->where($where)
//                ->order($sort, $order)
                ->limit($offset, $limit)
                ->select() ->toArray();
            $result = ['total' => $total, 'rows' => $list];
            return json($result);
        }
        $statusList = [
            '1' => '未审核',
            '2' => '审核通过',
            '3' => '审核未通过'
        ];
        $this -> assign('statusList',$statusList);
        return $this -> fetch();
    }


    public function add(){
        if ($this->request->isPost()) {
            $params = $this->request->post('row/a');
            if($params){
                $params['createtime'] =time();
                $this ->model -> insert($params);
                $this->success();
            }
            $this->error();
        }
        return $this -> fetch();
    }

    public function edit($ids=null){
        $row = $this->model->find($ids) ;
        if (! $row) {
            $this->error(__('No Results were found'));
        }
        if ($this->request->isPost()) {
            $params = $this->request->post('row/a');
            if($params){
                $params['updatetime'] = time();
                if(strpos($params['mch_id'],'*') !== false){
                    $params['mch_id'] = $row['mch_id'];
                }
                if(strpos($params['mch_key'],'*') !== false){
                    $params['mch_key'] = $row['mch_key'];
                }
                $result = $row -> save($params);
                if ($result === false) {
                    $this->error($row->getError());
                }
                $this->success();
            }
            $this->error();
        }
        $row['mch_id'] = substr_replace($row['mch_id'],"*******",0,4);
        $row['mch_key'] = substr_replace($row['mch_key'],"*******",0,4);
        $this->assign('row', $row);
        return $this-> fetch();
    }

    //软删除
    public function del($ids = ''){
        if ($ids) {
            $this->model -> where('id',$ids) -> update(['status' => 3,'deletetime' => time()]);
//            $this->model -> destroy($ids);
            $this->success();
        }
        $this->error();
    }
}
