<?php

namespace app\admin\controller\index;

use app\admin\model\WebsiteComments;
use app\common\controller\Backend;
use app\Request;

class Web extends Backend
{
    protected $model = null;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new WebsiteComments();
    }

    public function index (Request $request)
    {
        if ($request->isAjax()) {
            if ($request->request('keyField')) {
                return $this->selectpage();
            }
            [$where, $sort, $order, $offset, $limit] = $this->buildparams();
            $total = $this->model
                ->where($where)
                ->count();
            $list = $this->model
                ->where($where)
                ->order($sort, $order)
                ->limit($offset, $limit)
                ->select();
            $result = ['total' => $total, 'rows' => $list];
            return json($result);
        }
        return $this-> fetch();
    }

    public function add (Request $request)
    {
        if (!$request->isPost()) return apiBack('fail', 'Request错误', '10004');
        $param = $request->post();
        $param['status'] = 1;
        $res = $this->model->save($param);
        if ($res) {
            return apiBack('success', '留言成功', '10000');
        } else {
            return apiBack('fail', '失败', '10004');
        }
    }

    public function edit ($ids = null)
    {
        $row = $this->model->find($ids);
        if (! $row) {
            $this->error(__('No Results were found'));
        }

        if ($this->request->isPost()) {
            $params = $this->request->post('row/a');
            if ($params['status'] == 'normal') {
                $params['status'] = 1;
            } else {
                $params['status'] = 2;
            }
            $result = $row->save($params);
            if ($result === false) {
                $this->error($row->getError());
            }
            $this->success();
        }
        $this->assign('row', $row);
        return $this->fetch();
    }

    public function del ($ids = '')
    {
        if ($ids) {
            $this->model->destroy($ids);
            $this->success();
        }
        $this->error();
    }
}
