<?php
/**
 * Created by PhpStorm.
 * User: LENOVO
 * Date: 2020/10/5
 * Time: 22:06
 */
namespace app\admin\controller\product;

use app\common\controller\Backend;
use app\Request;
use fast\Tree;
use think\facade\Db;
//use app\admin\model\Category
class Category extends Backend
{
    protected $model = null;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\Category();
        $catelist = $this->model ->order('id', 'asc')->select()->toArray();
        Tree::instance()->init($catelist);
        $this->rulelist = Tree::instance()->getTreeList(Tree::instance()->getTreeArray(0), 'cate_name');
        $catedata = [0 => __('None')];
        foreach ($this->rulelist as $k => &$v) {
            $catedata[$v['id']] = $v['cate_name'];
        }
        unset($v);
        $this->assign('catedata', $catedata);
    }

    public function index (Request $request)
    {
        if ($request->isAjax()) {
            if ($request->request('keyField')) {
                return $this->selectpage();
            }
            [$where, $sort, $order, $offset, $limit] = $this->buildparams();
            $total = $this->model
                ->where($where)
                ->where('status', 1)
                ->count();
            $list = $this->model
                ->where($where)
                ->where('status', 1)
                ->order('createtime', 'desc')
                ->select();
            $result = ['total' => $total, 'rows' => $list];
            return json($result);
        }
        return $this-> fetch();
    }

    /**
     * 添加分类
     * @return string
     * @throws \Exception
     */
    public function add(){
        if ($this->request->isPost()) {
            $params = $this->request->post('row/a');
            if($params){
                $params['createtime'] = time();
                $result = $this->model->save($params);
                if ($result) {
                    $this->success();
                } else {
                    $this->error();
                }
            }
            $this->error();
        }
        return $this-> fetch();
    }

    /**
     * 分类编辑
     * @param null $ids
     * @return string
     * @throws \Exception
     */
    public function edit ($ids = null)
    {
        $row = $this->model->find($ids);
        if (! $row) {
            $this->error(__('No Results were found'));
        }
        if ($this->request->isPost()) {
            $params = $this->request->post('row/a');
            if($params){
                if (! $params['pid']) {
                    $this->error(__('The non-menu rule must have parent'));
                }
                $params['updatetime'] = time();
                $result =$row-> save($params);
                if ($result === false) {
                    $this->error($row->getError());
                }
                $this->success();
            }
        }
        $this->assign('row', $row);
        return $this->fetch();
    }

    /**
     * 删除类目
     * @param string $ids
     * @throws \Exception
     */
    public function del ($ids = '')
    {
        if ($ids) {
            $this->model->destroy($ids);
            $this->success();
        }
        $this->error();
    }
}
