<?php

return [
    'web_name' => '陕西天屿懿德科技网络有限公司',
    'web_desc' => '2',
    'configgroup' => [
        'basic' => 'Basic',
        'gongzhongho' => '微信公众号',
        'miniprogram' => '微信小程序',
        'dictionary' => 'Dictionary',
        'user' => 'User',
        'score' => '签到积分',
        'sekill' => '秒杀活动',
        'scoreConvert' => '积分兑换值',
        'share_money' => '邀人金额',
        'share_chicken_img' => '椒麻鸡分享图',
        'share_specialty_img' => '特产分享图',
    ],
    'web_key' => '',
    'categorytype' => [
        'default' => 'Default',
        'page' => 'Page',
        'article' => 'Article',
        'test' => 'Test',
    ],
    'cdnurl' => '',
    'version' => '1.0.1',
    'timezone' => 'Asia/Shanghai',
    'forbiddenip' => '',
    'languages' => [
        'backend' => 'zh-cn',
        'frontend' => 'zh-cn',
    ],
    'web_close' => '1',
    'web_logo' => '',
    'miniprogram_app_id' => 'wx2321f85bc3478c47',
    'miniprogram_app_secret' => '956390b077f68c3be27a819cf1043cc7',
    '新疆大枣' => [
    ],
    'sign_score' => '10',
    'skill_start' => '2020-11-20 20:00:00',
    'skill_end' => '2020-11-21 00:00:00',
    'scoreConvert' => '10000',
    'share_money' => '1',
    'share_chicken_img' => '/storage/uploads/20201126/53fdc5fc01bd9399591d08f650fe8df2.png',
    'share_specialty_img' => '/storage/uploads/20201126/c890ebc6cbe91fe9315df373aa139e29.png',
];