<?php
namespace app\api\controller;
use app\admin\model\Category;
use app\BaseController;
use app\common\SearchBuilders\ProductSearchBuilder;
//use app\Exceptions\InvalidRequestException;
//use Illuminate\Http\Request;
//use Illuminate\Pagination\LengthAwarePaginator;
use think\facade\Db;
use app\Request;
class Product extends BaseController{
    protected $model = null;
    public function initialize(){
        $this -> model = new \app\common\model\Product();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index(Request $request){

    }

//    public function show(Product $product,Request $request)
//    {
//        if (!$product->status) {
//            throw new InvalidRequestException("商品未上架");
//        }
//
//        if (!$product->audit_status) {
//            throw new InvalidRequestException("请等待商品审核");
//        }
//
//        $product = $product->where('id',$product->id)->with([
//            'skus',
//            'properties',
//            'images',
//            'productdescriptions'
//        ])->first();
//        $images = [];
//        foreach ($product->images as $key) {
//            foreach ($key->image_url as $value) {
//                $images[] = $value;
//            }
//        }
//
//        $address = $request->user()->addresses()->orderBy('last_used_at','desc')->get();
//
//        return view('products.productdetail',[
//            'product' => $product, //商品
//            'skus' => $product->skus, //商品sku
//            'properties' => $product->properties,//商品属性
//            'images' => $images,//商品详情页图片
//            'productdescriptions' => $product->productdescriptions,//商品详情
//            'addresses' => $address,
//        ]);
//    }
//
//    public function indexss(Request $request)
//    {
//        if ($request->isMethod('post')) {
//            $db = Product::where('id',$request->input('id'))->first()->toArray();
//            return json_encode($db);
//        }else{
//            return view('products.indexss');
//        }
//    }
}
